object Versions {
    val hiltNavigationCompose = "1.0.0-alpha03"
    val activityCompose = "1.4.0"
    val kotlin = "1.5.31"
    val coroutines = "1.5.2"
    val materialDialogs = "0.6.1"

    val core = "1.7.0-rc01"
    val material = "1.5.0-alpha04"
    val appCompat = "1.4.0-alpha02"
    val constraintLayout = "2.0.4"
    val lifecycle = "2.4.0-alpha02"
    val viewModelCompose = "2.4.0"
    val fragment = "1.4.0-alpha03"
    val mockk = "1.12.0"
    val hilt = "2.39.1"
    val testRunner = "1.3.0"
    val hiltJetpack = "1.0.0"
    val testJetpack = "2.1.0"
    val timber = "5.0.1"
    val initializer = "1.0.0-alpha01"
    val compose = "1.1.0-beta01"
    val hiltWork = "1.0.0"
    val hiltJetpackViewModel = "1.0.0-alpha03"
    val accompanistCoil = "0.15.0"
    val accompanistPager = "0.20.0"
    val workManager = "2.7.0"
    val room = "2.4.0-alpha03"

    val preferences = "1.1.1"
    val preferencesDataStore = "1.0.0"
    val truth = "1.4.0"
    val turbine = "0.6.1"
}


object Deps {
    val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
    val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
    val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    val core = "androidx.core:core-ktx:${Versions.core}"
    val viewModel = "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.viewModelCompose}"
    val lifecycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle}"
    val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    val material = "com.google.android.material:material:${Versions.material}"
    val hilt = "com.google.dagger:hilt-android:${Versions.hilt}"
    val hiltCompiler = "com.google.dagger:hilt-android-compiler:${Versions.hilt}"
    val hiltJetpackCompiler = "androidx.hilt:hilt-compiler:${Versions.hiltJetpack}"
    val hiltJetpackViewModel =
        "androidx.hilt:hilt-lifecycle-viewmodel:${Versions.hiltJetpackViewModel}"
    val hiltNavigationCompose =
        "androidx.hilt:hilt-navigation-compose:${Versions.hiltNavigationCompose}"
    val hiltWork = "androidx.hilt:hilt-work:${Versions.hiltWork}"
    val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    val appInitializer = "androidx.startup:startup-runtime:${Versions.initializer}"
    val preferences = "androidx.preference:preference-ktx:${Versions.preferences}"
    val preferencesDataStore = "androidx.datastore:datastore-preferences:${Versions.preferencesDataStore}"
    val composeActivity = "androidx.activity:activity-compose:${Versions.activityCompose}"
    val composeUi = "androidx.compose.ui:ui:${Versions.compose}"
    val composeFoundation = "androidx.compose.foundation:foundation:${Versions.compose}"
    val composeLayout = "androidx.compose.foundation:foundation-layout:${Versions.compose}"
    val composeRuntime = "androidx.compose.runtime:runtime:${Versions.compose}"
    val composeMaterial = "androidx.compose.material:material:${Versions.compose}"
    val composeMaterialIcons =
        "androidx.compose.material:material-icons-extended:${Versions.compose}"
    val composeUiTooling = "androidx.compose.ui:ui-tooling:${Versions.compose}"
    val accompanistCoil = "com.google.accompanist:accompanist-coil:${Versions.accompanistCoil}"
    val accompanistPager = "com.google.accompanist:accompanist-pager:${Versions.accompanistPager}"
    val accompanistPagerIndicators = "com.google.accompanist:accompanist-pager-indicators:${Versions.accompanistPager}"
    val workManager = "androidx.work:work-runtime-ktx:${Versions.workManager}"
    val fragment = "androidx.fragment:fragment-ktx:${Versions.fragment}"
    val roomRuntinme = "androidx.room:room-runtime:${Versions.room}"
    val roomCompiler = "androidx.room:room-compiler:${Versions.room}"
    val roomKtx = "androidx.room:room-ktx:${Versions.room}"
    val materialDialogsDatetime = "io.github.vanpra.compose-material-dialogs:datetime:${Versions.materialDialogs}"

    val junit = "junit:junit:4.13"
    val coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.coroutines}"
    val mockk = "io.mockk:mockk:${Versions.mockk}"
    val truth = "androidx.test.ext:truth:${Versions.truth}"
    val test = "androidx.arch.core:core-testing:${Versions.testJetpack}"
    val turbine = "app.cash.turbine:turbine:${Versions.turbine}"
    val androidTestRunner = "androidx.test:runner:${Versions.testRunner}"
    val androidTestRules = "androidx.test:rules:${Versions.testRunner}"
}